module.exports = {array: require('./array'),
  fs: require('./fs'),
  hash: require('./hash'),
  object: require('./object'),
  event: require('./event'),
  random: require('./random'),
  string: require('./string'),
  sys: require('./sys'),
  task: require('./task'),
  time: require('./time'),
  util: require('./util')}
